### ISSUE TITLE
Coverage report missing not tested files

### ISSUE THREAD

**Issue by dzolnjan** [kozlice/angular2-webpack-boilerplate#1]
Is there way to include into coverage report all .ts (not spec) files?

Right now only ones that are actually tested are included in report.

For example, if you delete app.component.spec.ts file (and run karma) it will show empty report but shouldn't report in that case contain:
1) app/app.component.ts > red 100%
2) app/app.service.ts > red 100%

**Comment by kozlice** [comment]
I'm in process of finding a solution, because this is an issue for me as well. I hope to figure it out during this week.

**Comment by dzolnjan** [comment]
I was experimenting with your repo and got to the point where all ts files are included report.
https://github.com/dzolnjan/angular2-webpack-boilerplate

**Comment by kozlice** [comment]
@dzolnjan Cool, thanks, I'll take a look at the changes you've made

**Comment by kozlice** [comment]
Made an update, code coverage for all source files is now generated.

**Comment by seetsy** [comment]
Ugh was trying to get this working for days. Thanks @dzolnjan you are a saint!

**Comment by pikopl** [comment]
Can you elaborate want exact change have you done it the source code to enable all ts files included in the report?

**Comment by kozlice** [comment]
@pikopl If I remember correctly, I've forced loading contents of `src` (not only modules required in tests, but everything) into an additional context in Karma's entry point. Code coverage in JSON format is generated, and then report is built from it (separately, in `posttest` command – can't remember why I couldn't make it work as a part of Karma run).

Here's the commit, which solved this issue: https://github.com/kozlice/angular2-webpack-boilerplate/commit/9ee8e513a59e4e6ced2675c47fe3a4ee3dab3acb
