### ISSUE TITLE
Running preinstall fails initial installation

### ISSUE THREAD

**Issue by nikneem** [kozlice/angular2-webpack-boilerplate#5]
When cloning and running npm install, npm will run 'npm run preinstall' which calls 'npm run clean' which performs a rimraf on several folders.

Then the npm install fails because the node_modules folder is missing. This is correct, because rimraf just removed that folder.

I changed the package.json file :
`"preinstall": "npm run clean",`
to
`"preinstall": "npm run clean:dist",`

and now it works fine.

**Comment by kozlice** [comment]
@nikneem Thanks, I'll fix this ASAP
